name = "CurveFit"
uuid = "5a033b19-8c74-5913-a970-47c3779ef25c"
version = "1.4.1"
authors = ["Paulo Jos√© Saiz Jabardo <pjabardo@gmail.com>, Avik Pal <avikpal@mit.edu> and contributors"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastRationals = "275e499e-7a09-5551-a1d1-9fe535a2b717"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NonlinearSolveBase = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"
NonlinearSolveFirstOrder = "5959db7a-ea39-4486-b5fe-2dd0bf03d60d"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
ADTypes = "1.20.0"
Aqua = "0.8.12"
CommonSolve = "0.2.6"
ConcreteStructs = "0.2.3"
DifferentiationInterface = "0.7.13"
Distributions = "0.25.122"
ExplicitImports = "1.11.2"
FastRationals = "0.3.0"
ForwardDiff = "1.3.0"
InverseFunctions = "0.1"
LinearAlgebra = "1.10"
LinearSolve = "3.15.0"
Markdown = "1.10.0"
NonlinearSolveBase = "2.0"
NonlinearSolveFirstOrder = "1.12"
RecursiveArrayTools = "3.33.0"
SciMLBase = "2.90"
Setfield = "1.1.2"
StatsAPI = "1.8.0"
Test = "1.10"
TestItemRunner = "1.1.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner", "Aqua", "ExplicitImports"]
